import { readFile, writeFile } from "node:fs/promises";
import { isDeepStrictEqual } from "node:util";

const schema = JSON.parse(await readFile(new URL("../schema/protocol.schema.json", import.meta.url), "utf8"));
const definitions = schema.$defs ?? {};

function typeFor(value) {
  if (value.$ref) return value.$ref.replace(/^#\/\$defs\//, "");
  if (value.const !== undefined) return JSON.stringify(value.const);
  if (value.enum) {
    const values = value.enum.map((entry) => JSON.stringify(entry));
    return value["x-open-enum"] ? `${values.join(" | ")} | (string & {})` : values.join(" | ");
  }
  if (value.oneOf) return value.oneOf.map(typeFor).join(" | ");
  if (value.anyOf) return value.anyOf.map(typeFor).join(" | ");
  if (value.type === "array") return `ReadonlyArray<${typeFor(value.items ?? {})}>`;
  if (value.type === "object" || value.properties) {
    const required = new Set(value.required ?? []);
    const properties = Object.entries(value.properties ?? {}).map(([name, property]) => {
      const optional = required.has(name) ? "" : "?";
      return `  ${JSON.stringify(name)}${optional}: ${typeFor(property)};`;
    });
    const additional = value.additionalProperties;
    if (additional && typeof additional === "object") properties.push(`  [key: string]: ${typeFor(additional)};`);
    else if (additional === true) properties.push("  [key: string]: unknown;");
    return properties.length > 0 ? `{
${properties.join("\n")}
}` : "Record<string, unknown>";
  }
  switch (value.type) {
    case "string": return "string";
    case "integer":
    case "number": return "number";
    case "boolean": return "boolean";
    case "null": return "null";
    default: return "unknown";
  }
}

const output = [
  "/* eslint-disable */",
  "// Generated by scripts/generate-types.mjs from schema/protocol.schema.json.",
  "// Do not edit this file directly; change the schema and regenerate.",
  "",
  `export const GENERATED_PROTOCOL_VERSION = ${schema.$defs.Capabilities.properties.protocolVersion.type === "integer" ? 1 : 0} as const;`,
  `export const GENERATED_ROUTES = ${JSON.stringify(schema["x-routes"] ?? [])} as const;`,
  ""
];

for (const [name, definition] of Object.entries(definitions)) {
  const value = typeFor(definition);
  if (definition.type === "object" || definition.properties) {
    output.push(`export interface ${name} ${value}`);
  } else {
    output.push(`export type ${name} = ${value};`);
  }
  output.push("");
}

const generated = `${output.join("\n").trimEnd()}\n`;
const outputURL = new URL("../src/types/generated.ts", import.meta.url);
if (process.argv.includes("--check")) {
  const current = await readFile(outputURL, "utf8").catch(() => "");
  if (current !== generated) {
    console.error("Generated types are stale. Run npm run generate.");
    process.exitCode = 1;
  }
} else {
  await writeFile(outputURL, generated);
}
